name: Quasi Params Test
on:
  pull_request: {}
  push:
    branches:
      - master
jobs:
  build-nix:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ghc:
          - ghc810
          - ghc88
          - ghc86
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"

      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"

      - name: Setup Cachix
        uses: "cachix/cachix-action@master"
        with:
          name: maybevoid
          extraPullNames: "iohk,maybevoid"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: Run Tests
        run: |
          nix-shell -A ${{ matrix.ghc }}.shell \
            --run "cabal run quasi-params-multi-test"
